{% set name = "aiobotocore" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3041333c565bff9d63b4468bee4944f2d81cff63a45b10e5cc652f3837f9cc2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=72.2.0
  run:
    - python >={{ python_min }}
    - aiohttp >=3.9.2,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.35.74,<1.35.89
    - wrapt >=1.10.10,<2.0.0

test:
  imports:
    - aiobotocore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  doc_url: http://aiobotocore.readthedocs.io
  dev_url: https://github.com/aio-libs/aiobotocore

extra:
  recipe-maintainers:
    - nehaljwani
